spring.application.name=stock-backend

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/test

jwt.secret=prTPt7xBIbeFkA3PhwwOoTg203v9eeZjwL5ZJMAK6Ig=

logging.level.org.springframework.security=DEBUG